package com.sites.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_case", "id", Case.class);
		arp.addMapping("t_case_evaluate", "id", CaseEvaluate.class);
		arp.addMapping("t_leave_message", "id", LeaveMessage.class);
		arp.addMapping("t_rticle", "id", Rticle.class);
		arp.addMapping("t_user", "id", User.class);
	}
}

