package com.sites.model;

import com.sites.model.base.BaseCase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Case extends BaseCase<Case> {
	public static final Case dao = new Case().dao();
}
