package com.sites.model;

import com.sites.model.base.BaseCaseEvaluate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CaseEvaluate extends BaseCaseEvaluate<CaseEvaluate> {
	public static final CaseEvaluate dao = new CaseEvaluate().dao();
}
