package com.sites.model;

import com.sites.model.base.BaseContent;

/**
 * Generated by JFinal.
 * @author duansongjiang
 */
@SuppressWarnings("serial")
public class Content extends BaseContent<Content> {
	public static final Content dao = new Content().dao();
}
