package com.sites.model;

import com.sites.model.base.BaseLeaveMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LeaveMessage extends BaseLeaveMessage<LeaveMessage> {
	public static final LeaveMessage dao = new LeaveMessage().dao();
}
