package com.sites.model;

import com.sites.model.base.BaseRticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rticle extends BaseRticle<Rticle> {
	public static final Rticle dao = new Rticle().dao();
}
