package com.sites.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRticle<M extends BaseRticle<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setContext(java.lang.String context) {
		set("context", context);
		return (M)this;
	}
	
	public java.lang.String getContext() {
		return getStr("context");
	}

	public M setClassification(java.lang.String classification) {
		set("classification", classification);
		return (M)this;
	}
	
	public java.lang.String getClassification() {
		return getStr("classification");
	}

	public M setCategory(java.lang.String category) {
		set("category", category);
		return (M)this;
	}
	
	public java.lang.String getCategory() {
		return getStr("category");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
